"""empty message

Revision ID: 470889cc8b0a
Revises: 5b38f0236806
Create Date: 2020-10-15 09:28:42.658808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470889cc8b0a'
down_revision = '5b38f0236806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=20), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
